repos:
  - repo: local
    hooks:
      - id: render-json-from-template
        name: Render JSON from templates
        entry: python bundle_script.py -r .
        language: system
        pass_filenames: false